import './PageStyles.css';

const TermsAndConditions = () => {
  return (
    <div className='privacy-page'>
      <h1>Krutsha Terms & Conditions</h1>

      <h2>Effective Date: 01-10-2025</h2>

      <h3>1. Introduction</h3>
      <p>By accessing or using Krutsha (“we,” “our,” “us”), you (“user,” “you”) agree to comply with and be bound by these Terms & Conditions. If you do not agree, you must stop using the platform immediately. These terms form a legally binding agreement governing your use of the platform.</p>

      <h3>2. Nature of Service</h3>
      <ul>
        <li>Krutsha provides an <strong>AI-powered platform</strong> that generates responses and insights based on user input.</li>
        <li>All content is <strong>generated automatically</strong> and may contain inaccuracies, omissions, or biases.</li>
        <li>Krutsha is not a human advisor and does not substitute for professional advice (medical, legal, financial, business, academic, or otherwise).</li>
      </ul>

      <h3>3. User Responsibilities</h3>
      <ul>
        <li>You are responsible for providing lawful, non-harmful, and accurate queries.</li>
        <li>You must not use Krutsha for illegal, harmful, abusive, or malicious purposes.</li>
        <li>You are solely responsible for how you interpret, share, or act upon the responses generated by Krutsha.</li>
        <li>You agree not to hold Krutsha liable for outcomes resulting from reliance on responses.</li>
      </ul>

      <h3>4. Response Accuracy & Limitations</h3>
      <ul>
        <li>Responses may include outdated information, factual errors, or fabricated (“hallucinated”) details.</li>
        <li>Content may not be contextually relevant, suitable, or accurate for your intended use.</li>
        <li>Krutsha does not guarantee that outputs will be error-free, usable, or tailored to individual circumstances.</li>
        <li>Verification of all responses is solely the user’s responsibility.</li>
      </ul>

      <h3>5. Restrictions on Use</h3>
      <p>You agree not to:</p>
      <ul>
        <li>Use Krutsha to create harmful, defamatory, extremist, discriminatory, or illegal content.</li>
        <li>Exploit AI outputs for harmful purposes such as misinformation, fraud, violence, or scams.</li>
        <li>Reverse engineer or attempt to extract proprietary models or code from Krutsha.</li>
        <li>Misrepresent Krutsha responses as authoritative advice without proper verification.</li>
      </ul>

      <h3>6. Liability Disclaimer</h3>
      <p>Krutsha, its partners, and affiliates <strong>shall not be liable</strong> for any:</p>
      <ul>
        <li><strong>Direct damages</strong> (financial losses, reputational damage, etc.).</li>
        <li><strong>Indirect damages</strong> (missed opportunities, contracts, or income).</li>
        <li><strong>Consequential damages</strong> (business risks, failed decisions, penalties, or lawsuits).</li>
        <li><strong>Incidental damages</strong> (technical errors, service downtime, or system malfunctions).</li>
        <li><strong>Reliance damages</strong> (loss suffered from assuming responses are accurate or complete).</li>
      </ul>
      <p>Users accept that <strong>all use of Krutsha is at their own risk</strong>.</p>

      <h3>7. Edge Cases Where Krutsha is Not Liable</h3>
      <ul>
        <li>Users relying solely on AI responses for professional, business, medical, or legal decisions.</li>
        <li>Losses incurred due to response errors, delays, or irrelevance.</li>
        <li>Misuse or misinterpretation of AI outputs by users or third parties.</li>
        <li>Technical interruptions, hacking incidents, or force majeure (natural disasters, strikes, internet failures).</li>
        <li>Data breaches or leaks despite reasonable security safeguards.</li>
        <li>Any claim that AI-generated content infringes third-party intellectual property rights.</li>
        <li>Violation of laws by users while relying on or distributing Krutsha outputs.</li>
      </ul>

      <h3>8. Intellectual Property</h3>
      <ul>
        <li>Krutsha retains exclusive rights over its platform, software, trademarks, and proprietary technology.</li>
        <li>AI-generated responses may be used by users, subject to compliance with these Terms, but are provided <strong>“as-is”</strong> without ownership claims from Krutsha.</li>
        <li>Users are fully responsible for how they use, adapt, or share generated content.</li>
      </ul>

      <h3>9. Service Availability</h3>
      <ul>
        <li>Krutsha does not guarantee uninterrupted availability of its services.</li>
        <li>Planned maintenance, unexpected outages, or system failures may occur without prior notice.</li>
        <li>Krutsha is not responsible for any impact caused by downtime.</li>
      </ul>

      <h3>10. Account & Termination</h3>
      <ul>
        <li>Users must provide accurate information during registration.</li>
        <li>Krutsha reserves the right to suspend or terminate accounts at its sole discretion for misuse or violation of terms.</li>
        <li>Termination does not affect limitations of liability or disclaimers outlined in these Terms.</li>
      </ul>

      <h3>11. Governing Law & Jurisdiction</h3>
      <ul>
        <li>These Terms shall be governed by and construed in accordance with the applicable laws of <strong>India</strong>.</li>
        <li>All disputes shall be subject to the exclusive jurisdiction of the courts in <strong>Hisar, Haryana</strong>.</li>
      </ul>

      <h3>12. Indemnification</h3>
      <p>You agree to indemnify and hold harmless Krutsha, its affiliates, employees, and partners from any claims, damages, losses, liabilities, or costs (including legal fees) arising from:</p>
      <ul>
        <li>Your use or misuse of Krutsha.</li>
        <li>Violation of these Terms.</li>
        <li>Infringement of third-party rights through usage of AI responses.</li>
      </ul>

      <h3>13. Modifications to Terms</h3>
      <ul>
        <li>Krutsha reserves the right to modify, amend, or update these Terms at any time.</li>
        <li>Significant updates may be notified through the platform or email.</li>
        <li>Continued use after changes implies acceptance of revised Terms.</li>
      </ul>

      <h3>14. Entire Agreement</h3>
      <p>These Terms, together with our Privacy Policy, constitute the entire agreement between the user and Krutsha. They supersede all prior understandings, communications, and agreements, written or oral.</p>
    </div>
  );
};

export default TermsAndConditions;
